Repository MYONGSIK/iOS, pull requests merged in 2023-04, with the labels that each got.

#103 [Chore] Firebase Analytics 추가
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/GoogleService-Info.plist
  MYONGSIK/Resource/Support/AppDelegate.swift
Labels: 💬 chore

#105 [Fix] 업데이트 혹은 삭제 후 재설치 마다 uuid 새롭게 들어가는 오류
  MYONGSIK/Resource/Support/AppDelegate.swift
  MYONGSIK/Resource/Support/RegisterUUID.swift
  Podfile
Labels: ❌ bug

#107 [Feature] 위젯 구현
  DailyFoodWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  DailyFoodWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  DailyFoodWidget/Assets.xcassets/Contents.json
  DailyFoodWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  DailyFoodWidget/Assets.xcassets/separator.imageset/Contents.json
  DailyFoodWidget/Assets.xcassets/separator.imageset/separator.svg
  DailyFoodWidget/DailyFoodWidget.swift
  DailyFoodWidget/DailyFoodWidgetBundle.swift
  DailyFoodWidget/DailyFoodWidgetLiveActivity.swift
  DailyFoodWidget/Info.plist
  DailyFoodWidget/RestaurantIntent.intentdefinition
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Info.plist
Labels: 💎 feat

#109 [fix] 지도 아이콘 표시 안되는 오류 수정
  MYONGSIK/Assets.xcassets/BottomIcons/map.imageset/Contents.json
  MYONGSIK/Assets.xcassets/BottomIcons/map.imageset/mapIcon.svg
Labels: ❌ bug

#111 [feature] 찜하기 cell 선택 시 상세 뷰 UI 구현
  MYONGSIK/Resource/Support/AppDelegate.swift
  MYONGSIK/Resource/Support/RegisterUUID.swift
  MYONGSIK/Source/Presentation/Heart/Cells/HeartListTableViewCell.swift
  MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift
  MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift
Labels: 💎 feat

#120 [fix] 지도 상세뷰 전화 버튼 화면 잘림 오류 수정
  MYONGSIK/Source/Presentation/Map/ViewController/MapStoreView.swift
Labels: ❌ bug

#123 [Feature] 업데이트 바텀 다이얼로그 화면 구현
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Assets.xcassets/Icons/update_map.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/update_map.imageset/update_map.svg
  MYONGSIK/Assets.xcassets/Icons/update_widget.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/update_widget.imageset/widget.svg
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/SelectRestaurantViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift
Labels: 💎 feat

#122 [Fix] 명지맛집 정렬 오류 처리 및 위젯 수정
  DailyFoodWidget/DailyFoodWidget.swift
  MYONGSIK/Source/Presentation/Main/Cells/SettingResTableViewCell.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/SettingRestautrantViewController.swift
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift
Labels: ❌ bug

#124 hot fix: 학관식당 조식/중식 라벨 변경
  DailyFoodWidget/DailyFoodWidget.swift
Labels: ❌ bug

#125 hot fix: 인캠 학식메뉴 back button hidden 처리
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
Labels: ❌ bug

#128 [fix] 위젯 설정 'DEAD CODE STRIPPING' - NO로 변경
  MYONGSIK.xcodeproj/project.pbxproj
Labels: ❌ bug

#130 [fix] heart 중복되는 오류 수정
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
  MYONGSIK/Source/Presentation/Map/ViewController/MapStoreView.swift
Labels: ❌ bug
