Repository MYONGSIK/iOS, pull requests merged in 2023-05, with the labels that each got.

#132 [Chore] 버전 1.1.9로 변경
  DailyFoodWidget/DailyFoodWidget.swift
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift
Labels: 💬 chore

#134 [Feature] 구글 광고 추가
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Info.plist
  MYONGSIK/Resource/Support/AppDelegate.swift
  MYONGSIK/Resource/Support/GoogleMobileAdsController.swift
  MYONGSIK/Resource/Support/GoogleMobileAdsKey.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/GaAdViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift
  Podfile
Labels: 💎 feat

#138 [Feature/Fix] 명지맛집 모음 UI 변경, 셀 마진 오류 처리
  MYONGSIK/Assets.xcassets/Icons/resIcon_bakery.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/resIcon_bakery.imageset/resIcon_bakery.svg
  MYONGSIK/Assets.xcassets/Icons/resIcon_cafe.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/resIcon_cafe.imageset/resIcon_cafe.svg
  MYONGSIK/Assets.xcassets/Icons/resIcon_drink.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/resIcon_drink.imageset/resIcon_drink.svg
  MYONGSIK/Assets.xcassets/Icons/resIcon_meal.imageset/Contents.json
  MYONGSIK/Assets.xcassets/Icons/resIcon_meal.imageset/resIcon_meal.svg
  MYONGSIK/Source/Presentation/Restaurant/Cells/SearchResultTableViewCell.swift
  MYONGSIK/Source/Presentation/Restaurant/Cells/TagTableViewCell.swift
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift
Labels: ❌ bug, 💎 feat

#140 [Fix] titleView 날짜 이동 버튼 event 재정의
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
Labels: ❌ bug

#141 [Fix] 스와이프 시 날짜 변경 이슈 처리
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
Labels: ❌ bug

#143 [Fix] 버전 업데이트 및 집밥 -> 맛집 수정
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Source/Presentation/Restaurant/Cells/TagTableViewCell.swift
Labels: 💬 chore

#145 [Fix] 일요일인 경우 차주 식단 조회 가능하도록 수정
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
Labels: ❌ bug

#146 [Fix] 일요일인 경우 차주 식단 조회 가능하도록 수정
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
Labels: ❌ bug

#148 [Update] 1.1.14 업데이트
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/SelectRestaurantViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift
  MYONGSIK/Source/Presentation/Utils/TabBarViewController.swift
Labels: 📋 docs, 💬 chore

#149 [Update] 1.1.14 메인 업데이트
  MYONGSIK.xcodeproj/project.pbxproj
  MYONGSIK/Resource/Support/RegisterUUID.swift
  MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/SelectRestaurantViewController.swift
  MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift
  MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift
  MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift
  MYONGSIK/Source/Presentation/Utils/TabBarViewController.swift
Labels: 💬 chore
